### ISSUE TITLE
Crash with memory allocation failed error

### ISSUE THREAD

**Issue by sparkymat** [vhakulinen/gnvim#111]
Built from git with master at `68e3fc8d2e8f6f7bbdd73641b00031c16004e8cc`

I have the FZF plugin enabled, which attempts to preview the file as well. When I attempt to preview a zip file that's 160MB large, it crashes with

```
memory allocation of 18446744073709551615 bytes failedfish: “gnvim” terminated by signal SIGABRT (Abort)
```

Looks like it tries to allocate (uint64)-1 .

Let me know if you need more info.

**Comment by sparkymat** [comment]
For reference, it works fine with `nvim 0.3.8`

**Comment by smolck** [comment]
> Built from git with master at `68e3fc8d2e8f6f7bbdd73641b00031c16004e8cc`

I assume you’re speaking of Neovim’s version here, is that right?

> Let me know if you need more info.

Could you provide a backtrace?

**Comment by smolck** [comment]
> I have the FZF plugin enabled, which attempts to preview the file as well. When I attempt to preview a zip file that's 160MB large, it crashes with
> 
> ```
> memory allocation of 18446744073709551615 bytes failedfish: “gnvim” terminated by signal SIGABRT (Abort)
> ```

`18446744073709551615` is the max value for a `u64` in Rust (see [here](https://doc.rust-lang.org/std/primitive.u64.html#examples-1)). It appears that it may be trying to allocate more memory into a `u64` than it can hold. Interested to see where this is happening.

**Comment by vhakulinen** [comment]
Interesting. I managed to reproduce it by trying to open 76MB large .tar.gz file. The invalid allocation is result of integer underflow.

**Comment by pranphy** [comment]
I use NERDTree plugin and when I try to open a file from the tree crashes with similar error.
```
memory allocation of 18446744073709551614 bytes failedAborted (core dumped)
```

**Comment by smolck** [comment]
@sparkymat Does this happen with the latest Neovim *release* (v0.4.3)? If so, could you run (assuming latest GNvim master) `RUST_LOG=gnvim=debug RUST_BACKTRACE=full cargo run` in the project directory and then provide the backtrace for the crash?

**Comment by ocehugo** [comment]
@smolck, I just faced this when a recursive grep hit a binary file by accident (neovim terminal).

Rust 1.41.1
Cargo 1.41.0
gnvim 0.1.0

```bash
RUST_BACKTRACE=1 target/debug/gnvim &> /dev/shm/rlog
# open neovim terminal, and cat a binary file
# cat /bin/ls
```
outcome is crash:
```rust
thread 'main' panicked at 'attempt to subtract with overflow', src/ui/grid/row.rs:86:47
stack backtrace:
   0:     0x5596c7ef6614 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5596c7ef6614 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5596c7ef6614 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x5596c7ef6614 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5596c7f1c1fc - core::fmt::write::h393d55821fa8e2cb
                               at src/libcore/fmt/mod.rs:1025
   5:     0x5596c7ef3e17 - std::io::Write::write_fmt::hc6645302c23e4504
                               at src/libstd/io/mod.rs:1426
   6:     0x5596c7ef87ae - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5596c7ef87ae - std::sys_common::backtrace::print::hc2635fd6c7743ade
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5596c7ef87ae - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
                               at src/libstd/panicking.rs:193
   9:     0x5596c7ef84a1 - std::panicking::default_hook::h66e3afff11b02e47
                               at src/libstd/panicking.rs:210
  10:     0x5596c7ef8e8b - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
                               at src/libstd/panicking.rs:471
  11:     0x5596c7ef8a3e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x5596c7f1825e - core::panicking::panic_fmt::he794217b0df3f806
                               at src/libcore/panicking.rs:84
  13:     0x5596c7f181aa - core::panicking::panic::h104b3bcaeb5f1ff0
                               at src/libcore/panicking.rs:51
  14:     0x5596c755c414 - gnvim::ui::grid::row::Leaf::split::h3d44f54cd9e01832
                               at src/ui/grid/row.rs:86
  15:     0x5596c755d4c1 - gnvim::ui::grid::row::Rope::split::he347eadaa059aeae
                               at src/ui/grid/row.rs:203
  16:     0x5596c755d9ff - gnvim::ui::grid::row::Rope::split::he347eadaa059aeae
                               at src/ui/grid/row.rs:215
  17:     0x5596c755f40f - gnvim::ui::grid::row::Row::insert_rope_at::hf4c271a7dc6b3277
                               at src/ui/grid/row.rs:376
  18:     0x5596c755fa65 - gnvim::ui::grid::row::Row::update::hafe16d20288d5abd
                               at src/ui/grid/row.rs:390
  19:     0x5596c7530c20 - gnvim::ui::grid::render::put_line::hdd53158066ac0733
                               at src/ui/grid/render.rs:194
  20:     0x5596c75bd9f9 - gnvim::ui::grid::grid::Grid::put_line::hedeffc347379adb2
                               at src/ui/grid/grid.rs:318
  21:     0x5596c75efd10 - gnvim::ui::ui::handle_redraw_event::{{closure}}::h3bcc0a44bb37c0bf
                               at src/ui/ui.rs:506
  22:     0x5596c764870a - core::iter::traits::iterator::Iterator::for_each::call::{{closure}}::hfded62f1ba7a1ac4
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/iter/traits/iterator.rs:629
  23:     0x5596c7645c08 - core::iter::traits::iterator::Iterator::fold::ok::{{closure}}::h2fa48d2f60940005
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/iter/traits/iterator.rs:1829
  24:     0x5596c753e1a7 - core::iter::traits::iterator::Iterator::try_fold::h900675a9c626c285
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/iter/traits/iterator.rs:1710
  25:     0x5596c7539cee - core::iter::traits::iterator::Iterator::fold::h6a52289691910673
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/iter/traits/iterator.rs:1832
  26:     0x5596c753adbc - core::iter::traits::iterator::Iterator::for_each::h17f2b097087d1138
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/iter/traits/iterator.rs:632
  27:     0x5596c7573fbe - gnvim::ui::ui::handle_redraw_event::h03a2f92511206d79
                               at src/ui/ui.rs:504
  28:     0x5596c757306c - gnvim::ui::ui::handle_notify::he237c2123bf39084
                               at src/ui/ui.rs:383
  29:     0x5596c75ef30c - gnvim::ui::ui::UI::start::{{closure}}::habcbf1bf0f6d8302
                               at src/ui/ui.rs:334
  30:     0x5596c7562f93 - glib::main_context_channel::dispatch::hf68a7754e7b0d197
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.8.0/src/main_context_channel.rs:282
  31:     0x7f5392e9db12 - g_main_context_dispatch
  32:     0x7f5392e9dda0 - <unknown>
  33:     0x7f5392e9de2f - g_main_context_iteration
  34:     0x7f53944cb8fd - g_application_run
  35:     0x5596c7611cc4 - <O as gio::application::ApplicationExtManual>::run::hda9bdb913665b088
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.7.0/src/application.rs:23
  36:     0x5596c75b3c9b - gnvim::main::hf04a84bd9b0ef978
                               at src/main.rs:198
  37:     0x5596c75a1f60 - std::rt::lang_start::{{closure}}::hacf364fc837995a6
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  38:     0x5596c7ef88d3 - std::rt::lang_start_internal::{{closure}}::h4aedff5d9863b36b
                               at src/libstd/rt.rs:52
  39:     0x5596c7ef88d3 - std::panicking::try::do_call::h0630fe3da32a089b
                               at src/libstd/panicking.rs:292
  40:     0x5596c7effd3a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  41:     0x5596c7ef9320 - std::panicking::try::hdfbe2fd873ac646c
                               at src/libstd/panicking.rs:270
  42:     0x5596c7ef9320 - std::panic::catch_unwind::hd7a9c10fa2bee1bc
                               at src/libstd/panic.rs:394
  43:     0x5596c7ef9320 - std::rt::lang_start_internal::hb8081e0e7e42ac0d
                               at src/libstd/rt.rs:51
  44:     0x5596c75a1f39 - std::rt::lang_start::he708ee4917e086ca
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  45:     0x5596c75b4f7a - main
  46:     0x7f5392c76e0b - __libc_start_main
  47:     0x5596c750f1aa - _start
  48:                0x0 - <unknown>
```
