### ISSUE TITLE
set title in init.vim / vimrc crashes

### ISSUE THREAD

**Issue by TyberiusPrime** [vhakulinen/gnvim#117]
How to reproduce:
add ```set title``` to your startup routine,
open with ```gnvim some_file.txt```
(it does not crash if you run just 'gnvim')

Workaround:
Don't set the title before the gui is there,
use ```autocmd GUIEnter * set title```
(edit: actually, that simply never get's executed ;) )

Trackback from debug build:
```
  0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:189
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:206
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:469
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:376
  12: rust_begin_unwind
             at src/libstd/panicking.rs:303
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: core::option::Option<T>::unwrap
             at /rustc/f3c9cece7b6829e6fd7854a1aee6a1619a81a38c/src/libcore/macros.rs:12
  16: gnvim::ui::grid::row::Rope::cell_at
             at src/ui/grid/row.rs:238
  17: gnvim::ui::grid::row::Row::cell_at
             at src/ui/grid/row.rs:334
  18: gnvim::ui::grid::grid::Grid::flush
             at src/ui/grid/grid.rs:122
  19: gnvim::ui::ui::handle_redraw_event
             at src/ui/ui.rs:661
  20: gnvim::ui::ui::handle_notify
             at src/ui/ui.rs:381
  21: gnvim::ui::ui::UI::start::{{closure}}
             at src/ui/ui.rs:332
  22: glib::main_context_channel::dispatch
             at /home/finkernagel/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.8.0/src/main_context_channel.rs:282
  23: g_main_context_dispatch
  24: <unknown>
  25: g_main_context_iteration
  26: g_application_run
  27: <O as gio::application::ApplicationExtManual>::run
             at /home/finkernagel/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.7.0/src/application.rs:23
  28: gnvim::main
             at src/main.rs:180
  29: std::rt::lang_start::{{closure}}
             at /rustc/f3c9cece7b6829e6fd7854a1aee6a1619a81a38c/src/libstd/rt.rs:61
  30: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  31: std::panicking::try::do_call
             at src/libstd/panicking.rs:288
  32: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  33: std::panicking::try
             at src/libstd/panicking.rs:267
  34: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  35: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  36: std::rt::lang_start
             at /rustc/f3c9cece7b6829e6fd7854a1aee6a1619a81a38c/src/libstd/rt.rs:61
  37: main
  38: __libc_start_main
  39: _start
```

**Comment by smolck** [comment]
Could you try #103’s branch and see if that fixes the issue?

**Comment by TyberiusPrime** [comment]
Yes, it also happens with python files,
but #103 fixes it!

**Comment by smolck** [comment]
What version of Neovim and GNvim are you using?

**Comment by TyberiusPrime** [comment]
nvim 0.3.8
and gnvim commit 7b89a6de910252acf86c5035155b9df63fd46f31

**Comment by TyberiusPrime** [comment]
It does not persist with the current nvim nightly.

**Comment by smolck** [comment]
That’s what I figured. The crashes occurring at the location this one does might have been a Neovim issue in older versions, and so #103 may not get merged; I’m not sure, depends on what @vhakulinen thinks about all this. See https://github.com/vhakulinen/gnvim/issues/92#issuecomment-545418411 (and the other comments if you want more info).

**Comment by vhakulinen** [comment]
Can you test with nvim 0.4 and the latest master of gnvim?

**Comment by TyberiusPrime** [comment]
Latest master works on nvim 0.4, but crashes on 0.3.8

**Comment by smolck** [comment]
Could you provide a stacktrace?

**Comment by TyberiusPrime** [comment]
Sure.
```env RUST_BACKTRACE=1 gnvim run.py --nvim /usr/bin/nvim
Not supported option set: arabicshape
Not supported option set: ambiwidth
Not supported option set: emoji
Not supported option set: guifontset
Not supported option set: guifontwide
Not supported option set: showtabline
Not supported option set: termguicolors
Not supported option set: ext_linegrid
Not supported option set: ext_hlstate
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: termguicolors
Received unknown redraw event: set_icon
Received unknown redraw event: set_icon
Received unknown redraw event: set_icon
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:189
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:206
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:469
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:376
  12: rust_begin_unwind
             at src/libstd/panicking.rs:303
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: gnvim::ui::grid::row::Rope::cell_at
  16: gnvim::ui::grid::grid::Grid::flush
  17: gnvim::ui::ui::handle_notify
  18: glib::main_context_channel::dispatch
  19: g_main_context_dispatch
  20: <unknown>
  21: g_main_context_iteration
  22: g_application_run
  23: <O as gio::application::ApplicationExtManual>::run
  24: gnvim::main
  25: std::rt::lang_start::{{closure}}
  26: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  27: std::panicking::try::do_call
             at src/libstd/panicking.rs:288
  28: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  29: std::panicking::try
             at src/libstd/panicking.rs:267
  30: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  31: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  32: main
  33: __libc_start_main
  34: _start
```

**Comment by smolck** [comment]
Thank you! That sort of stuff really helps us out ;)

Interesting. I thought that #103 would fix this crash, since (see line 15 of stacktrace) it appears to be happening at the same line as the crash(es) that PR is supposed to fix.

I’m guessing it’s happening here (at `.unwrap()`):
https://github.com/vhakulinen/gnvim/blob/16b465b967533386f380a1696b9f7c7b9b89e77e/src/ui/grid/row.rs#L238-L244

Would you mind putting `dbg!(&leaf, &leaf.text.chars());` above this line here and giving the output?: https://github.com/vhakulinen/gnvim/blob/16b465b967533386f380a1696b9f7c7b9b89e77e/src/ui/grid/row.rs#L238

**Comment by TyberiusPrime** [comment]
You know what, I shouldn't debug before my morning coffee. Git master is working fine with nvim 0.3.8, You just need to actually start the git master and not /usr/local/bin/gnvim... sorry about that.

Guess this can be closed.

**Comment by smolck** [comment]
> You know what, I shouldn't debug before my morning coffee. Git master is working fine with nvim 0.3.8, You just need to actually start the git master and not /usr/local/bin/gnvim... sorry about that.

No problem, it’s all good! ;) Thanks for submitting this issue!
