### ISSUE TITLE
Crash: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ui/grid/grid.rs:134:55

### ISSUE THREAD

**Issue by raghur** [vhakulinen/gnvim#193]
Crashes on startup most of the times. Fresh installation on manjaro. I've seen it work once in a while - usually just the first time - so my guess is some sort of race/concurrency issue.

Neovim in terminal is fine.
```
% gnvim --version                                                                                                                                                   
gnvim v0.1.6

% nvim --version                                                                                                                                                    [7:46:25 AM]|(BINARY-N/A)
Found existing alias for "nvim". You should use: "vim"
NVIM v0.8.0-dev-872-gbccb5de89
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az132-430

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

```
% RUST_BACKTRACE=full gnvim                                                                                                                                         [7:43:31 AM]|(BINARY-N/A)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ui/grid/grid.rs:134:55
stack backtrace:
   0:     0x55c37a17f42d - <unknown>
   1:     0x55c37a1a13ac - <unknown>
   2:     0x55c37a17cb81 - <unknown>
   3:     0x55c37a180ae5 - <unknown>
   4:     0x55c37a180806 - <unknown>
   5:     0x55c37a181076 - <unknown>
   6:     0x55c37a180f29 - <unknown>
   7:     0x55c37a17f8e4 - <unknown>
   8:     0x55c37a180c99 - <unknown>
   9:     0x55c379f48843 - <unknown>
  10:     0x55c379f4870d - <unknown>
  11:     0x55c379f5e6c3 - <unknown>
  12:     0x55c379fbad95 - <unknown>
  13:     0x55c379fb86ad - <unknown>
  14:     0x55c379fa8cbe - <unknown>
  15:     0x7fbcc341fc6b - g_main_context_dispatch
  16:     0x7fbcc3476001 - <unknown>
  17:     0x7fbcc341d392 - g_main_context_iteration
  18:     0x7fbcc4c0d30e - g_application_run
  19:     0x55c379f748be - <unknown>
  20:     0x55c379f61572 - <unknown>
  21:     0x55c379f726b3 - <unknown>
  22:     0x55c379f772a9 - <unknown>
  23:     0x55c37a17869e - <unknown>
  24:     0x55c379f61d42 - <unknown>
  25:     0x7fbcc30fd2d0 - <unknown>
  26:     0x7fbcc30fd38a - __libc_start_main
  27:     0x55c379f48a95 - <unknown>
  28:                0x0 - <unknown>
```

**Comment by vhakulinen** [comment]
Gnvim was rewritten from ground up for gtk4. If the problem persists, feel free to reopen this issue.
