### ISSUE TITLE
Failed to attach UI: NeovimError(1, "No such UI option: ext_linegrid")

### ISSUE THREAD

**Issue by chino540off** [vhakulinen/gnvim#20]
Hello,

I have issues with awesome wm, and gnvim.
My awesome version (ubuntu 18.04) is v4.2

Here is my backtrace:
```
sh$ RUST_BACKTRACE=1 ./target/debug/gnvim --print-nvim-cmd
nvim cmd: "nvim" "--embed" "--cmd" "let g:gnvim=1" "--cmd" "set termguicolors" "--cmd" "let &rtp.=\',/usr/local/share/gnvim/runtime\'"
thread 'main' panicked at 'Failed to attach UI: NeovimError(1, "No such UI option: ext_linegrid")', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::expect
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:825
  10: gnvim::build
             at src/main.rs:119
  11: gnvim::main::{{closure}}
             at src/main.rs:139
  12: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/ops/function.rs:240
  13: gio::auto::application::activate_trampoline
             at /home/olivier/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.5.1/src/auto/application.rs:526
  14: g_closure_invoke
  15: <unknown>
  16: g_signal_emit_valist
  17: g_signal_emit
  18: <unknown>
  19: g_application_run
  20: <O as gio::application::ApplicationExtManual>::run
             at /home/olivier/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.5.1/src/application.rs:23
  21: gnvim::main
             at src/main.rs:142
  22: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  23: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  25: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  26: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  27: main
  28: __libc_start_main
  29: _start
```

Do you have any idea about this error?

Regards,

**Comment by bfredl** [comment]
What is your nvim version? You will need nvim 0.3.2 or later (the latest 0.3.4 is recommended)

**Comment by chino540off** [comment]
You right, i was in 0.3.1, and i get the 0.3.4, it works perfectly,

Thanks
