### ISSUE TITLE
crash after insert (with --disable-ext-tabline)

### ISSUE THREAD

**Issue by last-partizan** [vhakulinen/gnvim#81]
When i do this:
```
RUST_BACKTRACE=1 GNVIM_RUNTIME_PATH=/home/serg/work/git/gnvim/runtime cargo run -- --disable-ext-tabline ~/minimal.vimrc
```
and then `:tabedit ~/.vimrc`, select this lines

```
filetype plugin indent on
if !exists("g:syntax_on")
  syntax enable
endif
```
go back to previous tab and press `p` for insert, gnvim crashes with following backtrace.

<details>
<summary>Backtrace</summary>

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/gnvim --disable-ext-tabline /home/serg/minimal.vimrc`
Not supported option set: arabicshape
Not supported option set: ambiwidth
Not supported option set: emoji
Not supported option set: guifontset
Not supported option set: guifontwide
Not supported option set: showtabline
Not supported option set: termguicolors
Not supported option set: ext_linegrid
Not supported option set: ext_hlstate
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: termguicolors
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Not supported option set: ext_cmdline
Not supported option set: ext_popupmenu
Not supported option set: ext_tabline
Not supported option set: ext_wildmenu
Failed to turn input event into nvim key (keyval: 65506)
Failed to turn input event into nvim key (keyval: 65505)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: core::option::Option<T>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:12
  10: gnvim::ui::grid::row::Rope::cell_at
             at src/ui/grid/row.rs:238
  11: gnvim::ui::grid::row::Rope::cell_at
             at src/ui/grid/row.rs:251
  12: gnvim::ui::grid::row::Rope::cell_at
             at src/ui/grid/row.rs:251
  13: gnvim::ui::grid::row::Rope::cell_at
             at src/ui/grid/row.rs:251
  14: gnvim::ui::grid::row::Row::cell_at
             at src/ui/grid/row.rs:334
  15: gnvim::ui::grid::grid::Grid::flush
             at src/ui/grid/grid.rs:124
  16: gnvim::ui::ui::handle_redraw_event
             at src/ui/ui.rs:674
  17: gnvim::ui::ui::handle_notify
             at src/ui/ui.rs:410
  18: gnvim::ui::ui::UI::start::{{closure}}::{{closure}}
             at src/ui/ui.rs:346
  19: glib::source::trampoline
             at /home/serg/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.8.0/src/source.rs:105
  20: g_main_context_dispatch
  21: <unknown>
  22: g_main_context_iteration
  23: g_application_run
  24: <O as gio::application::ApplicationExtManual>::run
             at /home/serg/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.7.0/src/application.rs:23
  25: gnvim::main
             at src/main.rs:156
  26: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  27: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  28: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  29: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  30: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  31: main
  32: __libc_start_main
  33: _start
```
</details>

Without `--disable-ext-tabline` it does not crash.

**Comment by smolck** [comment]
Hmm, can't seem to reproduce this. But, it appears to be happening at [this unwrap](https://github.com/vhakulinen/gnvim/blob/master/src/ui/grid/row.rs#L238) from looking at the backtrace you showed. @vhakulinen would know more about this, I don't know whether or not that unwrap should be an `unwrap_or` instead (which, if given a correct default value to use when the `unwrap` fails, should fix your problem). That could be an oversight (and an oversight that would probably make this crash a hard one to reproduce), but it's also possible that somewhere down the line a wrong value is passed around that causes this unwrap to fail when it shouldn't (again, making this a hard-to-reproduce issue). If the latter case is true then using `unwrap_or` wouldn't fix the underlying problem.

@badosu Can you reproduce this?

**Comment by last-partizan** [comment]
Looks like this unwrap displaying current symbol at cursor.
I changed it to:
```
                let empty_set_char = "∅".chars().next().unwrap();
                let c = dbg!(leaf.text.chars().nth(at - 1).unwrap_or(empty_set_char));
```

And it not crashed, and debug log is this:
```
[src/ui/grid/row.rs:239] leaf.text.chars().nth(at - 1).unwrap_or(empty_set_char) = 'f'
[src/ui/grid/row.rs:239] leaf.text.chars().nth(at - 1).unwrap_or(empty_set_char) = ' '
[src/ui/grid/row.rs:239] leaf.text.chars().nth(at - 1).unwrap_or(empty_set_char) = ' '
[src/ui/grid/row.rs:239] leaf.text.chars().nth(at - 1).unwrap_or(empty_set_char) = ' '
[src/ui/grid/row.rs:239] leaf.text.chars().nth(at - 1).unwrap_or(empty_set_char) = '∅'
[src/ui/grid/row.rs:239] leaf.text.chars().nth(at - 1).unwrap_or(empty_set_char) = 'f'
[src/ui/grid/row.rs:239] leaf.text.chars().nth(at - 1).unwrap_or(empty_set_char) = 'f'
```

**Comment by badosu** [comment]
I was not able to reproduce error, but at the same time I don't have `~/minimal.vimrc` and `~/.vimrc`, also you said press `p` for insert but it pastes so perhaps some content should be copied beforehand?

**Comment by last-partizan** [comment]
Yes, i mean 'p for paste'. From .vimrc i was copying this
```
filetype plugin indent on
if !exists("g:syntax_on")
  syntax enable
endif
```

**Comment by last-partizan** [comment]
Today i'm unable to reproduce it either.

Probably it was fixed by neovim-nightly update. I'm closing this issue.
