### ISSUE TITLE
Occasional panic in WebKit Javascript

### ISSUE THREAD

**Issue by YaLTeR** [vhakulinen/gnvim#88]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { domain: WebKitJavascriptError, code: 699, message: "SyntaxError: Can\'t create duplicate variable: \'width\'" }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  10: <O as webkit2gtk::auto::web_view::WebViewExt>::run_javascript::run_javascript_trampoline
  11: <unknown>
  12: <unknown>
  13: g_task_return_new_error
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: _ZN3WTF7RunLoop11performWorkEv
  24: <unknown>
  25: g_main_context_dispatch
  26: <unknown>
  27: g_main_context_iteration
  28: g_application_run
  29: <O as gio::application::ApplicationExtManual>::run
  30: gnvim::main
  31: std::rt::lang_start::{{closure}}
  32: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  34: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  35: main
  36: __libc_start_main
  37: _start
```

**Comment by vhakulinen** [comment]
Can you give any steps to reproduce this? I'm quite sure how to fix this, but I also want to know the situation where this happens.

**Comment by YaLTeR** [comment]
I don't have a clear test-case. It was happening mainly when I was triggering `rust-analyzer` completions. Perhaps something with my setup with automatic hover popups and completions interacting in a bad way.

**Comment by vhakulinen** [comment]
Which webkit2gtk version do you have?

**Comment by YaLTeR** [comment]
`2.24.3-1`

**Comment by vhakulinen** [comment]
The webkit stuff was removed in 8014a4d0fa2eec83e9c64adf66c2fca891dcbc73
